import { APIGatewayProxyEvent } from 'aws-lambda';

export const createAPIGatewayProxyEvent = (pathParameters?: { [name: string]: string }): APIGatewayProxyEvent => ({
  pathParameters: pathParameters || null,
  body: null,
  headers: {},
  multiValueHeaders: {},
  httpMethod: 'GET',
  isBase64Encoded: false,
  path: '/',
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  stageVariables: null,
  requestContext: {
    accountId: '123456789012',
    apiId: 'api-id',
    authorizer: {},
    protocol: 'HTTP/1.1',
    httpMethod: 'GET',
    identity: {
      accessKey: null,
      accountId: null,
      apiKey: null,
      apiKeyId: null,
      caller: null,
      clientCert: null,
      cognitoAuthenticationProvider: null,
      cognitoAuthenticationType: null,
      cognitoIdentityId: null,
      cognitoIdentityPoolId: null,
      principalOrgId: null,
      sourceIp: '127.0.0.1',
      user: null,
      userAgent: null,
      userArn: null,
    },
    path: '/',
    stage: 'dev',
    requestId: 'request-id',
    requestTimeEpoch: 1631234567890,
    resourceId: 'resource-id',
    resourcePath: '/',
  },
  resource: '/'
});
